#!/bin/bash
#SBATCH --time=1:30:00
#SBATCH --partition=broadwl
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=12gb
#SBATCH --mail-type=all
#SBATCH --mail-user=letitiayhho@uchicago.edu
#SBATCH --output=logs/%j.log

set -exuo pipefail

module load python
module load parallel

if [[ $# -ne 3 ]]; then
  echo "usage: $0 <sub> <task> <run>"
  exit 1
fi

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

sub="$1"
task="$2"
run="$3"

module load python

python preprocessing/preprocess.py "$sub" "$task" "$run"

printf "\n\n Preprocessing complete \n\n"
