#!/bin/bash

set -exuo pipefail

GIT_HOME="$(git rev-parse --show-toplevel)"
cd "$GIT_HOME" || exit

# retrieve filenames

job_id=$(date +%s)

for file in filenames; do
  preprocess_one_subject "$file" &> preprocessing/logs/main_"$job_id".log
  & # do I need this?
done
