#!/bin/bash
#SBATCH --partition=broadwl
#SBATCH --job-name=test
#SBATCH --mail-type=ALL
#SBATCH --mail-user=letitiayhho@uchicago.edu
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=10mb
#SBATCH --time=00:00:10
#SBATCH --output=test_%j.log

pwd
hostname
date
echo "test"
job_id=$(date +%s)
echo "$job_id"
job_id=$SLURM_JOB_NAME
echo $job_id
date
