#!/usr/bin/env python3

from pathlib import Path
import shutil
import os
import re

files = Path("../data/captrak")

for file in files.iterdir():
    file = str(file)
    if 'CapTrakResultFile' not in file:
        continue
    new_file = str(Path(file).parent) + '/' + file.split('_')[-1]
    shutil.move(
        file,
        new_file,
        )
    print(f"Renamed {file} to {new_file}")
